USE [QBXML]
GO
/****** Object:  StoredProcedure [dbo].[04CreateQBXMLAirInvoices]    Script Date: 12/11/2015 3:32:39 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [dbo].[04CreateQBXMLInvoices]
AS
BEGIN
	SET NOCOUNT ON;
SELECT DISTINCT 1 AS Tag,
       NULL AS Parent,
       'stopOnError' AS [QBXMLMsgsRq!1!onError],
	   NULL AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   NULL AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   NULL AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 2 AS Tag,
       1 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 3 AS Tag,
       2 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 4 AS Tag,
       3 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 5 AS Tag,
       3 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   TemplateRef AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 6 AS Tag,
       3 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   (SELECT CONVERT(VARCHAR(10), InvoiceDate, 120))  AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!6!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 7 AS Tag,
       3 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 8 AS Tag,
       3 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   ServiceTeam AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 9 AS Tag,
       3 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   Printed AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 10 AS Tag,
       3 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   Emailed AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   NULL AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT 11 AS Tag,
       3 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   P_Id AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT  12 AS Tag,
        11 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   P_Id AS [InvoiceLineAdd!11!Sort!hide],
	   ProductCategory AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT 13 AS Tag,
       11 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   P_Id AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   CONVERT (VARCHAR(16),LogDate,120)+' '+ISNULL (DisplayID,'')+' '+ISNULL (ApplicantLastName,'')+', '+ISNULL (ApplicantFirstName,'')+' '+ISNULL (ProductDescription,UpgradeReason)+' '+ISNULL (UserID,'')+' '+ISNULL (LoanNumber,'') AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!16!!element],
	   NULL AS [Other2!17!!element]
FROM   BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT 14 AS Tag,
       11 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   P_Id AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   '1' AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 15 AS Tag,
       11 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   P_Id AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   Price AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 16 AS Tag,
       11 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   P_Id AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   Department AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 17 AS Tag,
       11 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   P_Id AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   Payment AS [Other1!17!!element],
	   NULL AS [Other2!18!!element]
FROM BillingData 
WHERE ServiceTeam LIKE 'AIR'
UNION ALL
SELECT DISTINCT 18 AS Tag,
       11 AS Parent,
	   NULL AS [QBXMLMsgsRq!1!onError],
	   0 AS [InvoiceAddRq!2!requestID],
	   NULL AS [InvoiceAdd!3!InvoiceAdd!element],
	   CompanyName AS [CustomerRef!4!FullName!element],
	   NULL AS [TemplateRef!5!FullName!element],
	   NULL AS [TxnDate!6!!element],
	   InvoiceNumber AS [RefNumber!7!!element],
	   NULL AS [SalesRepRef!8!FullName!element],
	   NULL AS [IsToBePrinted!9!!element],
	   NULL AS [IsToBeEmailed!10!!element],
	   NULL AS [InvoiceLineAdd!11!],
	   P_Id AS [InvoiceLineAdd!11!Sort!hide],
	   NULL AS [ItemRef!12!FullName!element],
	   NULL AS [Desc!13!!element],
	   NULL AS [Quantity!14!!element],
	   NULL AS [Rate!15!!element],
	   NULL AS [ClassRef!16!FullName!element],
	   NULL AS [Other1!17!!element],
	   (SELECT CONVERT(VARCHAR(10), LogDate, 120)) AS [Other2!18!!element]
FROM BillingData WHERE ServiceTeam LIKE 'AIR'	   
ORDER BY [CustomerRef!4!FullName!element],[RefNumber!7!!element],[InvoiceLineAdd!11!Sort!hide], Tag
FOR XML EXPLICIT, ROOT ('QBXML')
END
